name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20  # Match your Dockerfile version
      
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Set up Docker Compose (optional if compose is already included in the runner)
    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    # Build and push the Docker image using docker-compose
    - name: Build and Push Docker Image with Docker Compose
      run: |
       docker-compose build
       docker tag coachboard_fe tahirli/coachboard_fe:latest
       docker push tahirli/coachboard_fe:latest


    # Deploy to Production Server
    - name: Deploy to Production Server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_PROD_HOST }}
        username: ${{ secrets.SERVER_PROD_USERNAME }}
        password: ${{ secrets.SERVER_PROD_PASSWORD }}
        port: ${{ secrets.SERVER_PROD_PORT }}
        script: |
          # Production-specific deployment script
          cd /root/coachboard/frontend/prod
          docker pull tahirli/coachboard_fe:latest
          docker compose down
          docker compose up -d